#!/bin/bash

function runTests() {
    stack test --silent --fast 2>/dev/null
}

function wip() {
    git add . && git commit -m "Limbo-ing! See tags/releases for what you'd normally expect in a commit message."
}

function revert() {
    git reset --hard
}

function tc() {
    runTests || ( local RET=$?; stack test; return $RET; ) && echo && wip
}

function tcr() {
    tc || revert
}

function tcr-sync() {
        reset

        tcr
        TCR_RET=$?

        while ( ! git pull -q --rebase ); do
            echo "Press <enter> to re-try the pull."
            read
        done
        
        if [[ $TCR_RET -eq 0 ]]; then
            runTests >/dev/null || ( clear; runTests ; false; ) && git push
        fi
}

function limbo() {
    while : ; do
        tcr-sync
        
        echo
        read -s -p "<enter> to test && commit || revert "
    done
}
